# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# Notes:
# - The master branch has to have a config or it won't even see other branches
# - CircleCI requires a follower before it will build a project
# - There is a CLI for testing config schema locally - https://circleci.com/docs/2.0/local-cli/#section=configuration


# 2.1 vs. 2.0 - https://discuss.circleci.com/t/circleci-2-1-config-overview/26057
# 
# Spec now includes:
#   orbs
#   commands
#   executors
#   jobs

# Version 2.1 moves towards a single version at the top of the file vs. under workflow
version: 2.1

#
# Executors
#

executor_defaults: &executor_defaults
  # TO DO - Is there any benefit to this being the name of the actual project?
  working_directory: ~/repo

  environment:
    - GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1

# Node Images - https://circleci.com/docs/2.0/circleci-images/#nodejs
# Variants - https://circleci.com/docs/2.0/circleci-images/#language-image-variants
executors:
  node10:
    <<: *executor_defaults
    docker:
      - image: circleci/node:10

  node10browsers:
    <<: *executor_defaults
    docker:
      - image: circleci/node:10-browsers

commands: 
  setup_ci_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6a:ca:a9:d4:15:97:96:e1:1d:0f:af:e5:85:27:88:d4"

  install_nr1cli:
    steps:
      - run:
          name: "Install NR1 CLI"
          command: |
            curl -s https://cli.nr-ext.net/installer.sh | bash

  validate_os_schema:
    steps:
      - run:
          name: "Checking for all the necessary OSS bits"
          command: |
            FILE=~/repo/LICENSE
            if [ -f "$FILE" ]; then
                echo "$FILE exists"
            fi

            FILE=~/repo/THIRD_PARTY_NOTICES.md
            if [ -f "$FILE" ]; then
                echo "$FILE exists"
            fi

jobs:
  setup:
    executor: node10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - install_nr1cli

  build:
    executor: node10browsers

    steps:
      - install_nr1cli

  validate:
    executor: node10browsers

    steps:
      - validate_os_schema

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10-browsers
    steps:
      # We don't have tests yet, but we should
      - run: npm test

  contributors:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: Generate Contributors
          command: |
            echo 'Generating a list of contributors'

workflows:
  # A merge or commit to the master branch
  # release:
  #   jobs:
  #     - setup:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - build:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - generate_release:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - version:
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - deploy:
  #         filters:
  #           branches:
  #             only:
  #               - master
  
  # Test and Analyze the current state
  test:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
                - master

      - build:
          filters:
            branches:
              ignore:
                - master

      - validate:
          filters:
            branches:
              ignore:
                - master

  # pr_from_fork:
  #   jobs:
  #     - setup:
  #         filters:
  #           branches:
  #             only: /pull\/[0-9]+/

  #     - test:
  #         filters:
  #           branches:
  #             only: /pull\/[0-9]+/

  #     - validate:
  #         filters:
  #           branches:
  #             only: /pull\/[0-9]+/