# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# Gotchas:
# - The master branch has to have a config or it won't see other branches config files
# - CircleCI requires a follower before it will build a project


# Testing
# There is a CLI for testing config schema locally - https://circleci.com/docs/2.0/local-cli/#section=configuration
# Run `circleci config validate` from the project folder


# 2.1 vs. 2.0 - https://discuss.circleci.com/t/circleci-2-1-config-overview/26057
# 
# Spec now includes:
#   orbs
#   commands
#   executors
#   jobs

# Version 2.1 moves towards a single version at the top of the file vs. under workflow
version: 2.1

# 
# Configs
# 

github-semantic-bot: &github-semantic-bot
  GIT_AUTHOR_NAME: "@semantic-release-bot"
  # GIT_AUTHOR_EMAIL: "@semantic-release-bot email address"
  GIT_COMMITTER_NAME: "@semantic-release-bot"
  # GIT_COMMITTER_EMAIL: "@semantic-release-bot email address"
    

# 
# Orbs
# 
# orbs:
# "Orb snyk/snyk@0.0.8 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings."
#   snyk: snyk/snyk@0.0.8


#
# Executors
#

executor_defaults: &executor_defaults
  environment:
    - GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1

# Node Images - https://circleci.com/docs/2.0/circleci-images/#nodejs
# Variants - https://circleci.com/docs/2.0/circleci-images/#language-image-variants
executors:
  node10:
    <<: *executor_defaults
    docker:
      - image: circleci/node:10

  node10browsers:
    <<: *executor_defaults
    docker:
      - image: circleci/node:10-browsers

commands: 
  # Download and cache source code
  command-restore-or-checkout:
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

  # Download and cache dependencies
  command-install:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      # "Orb snyk/snyk@0.0.8 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings."
      # - snyk/scan

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # Add ssh key with write access
  # Note: only to be used on merges to master, i.e. it has been reviewed by a NewRelic maintainer
  command-setup-ci-keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6a:ca:a9:d4:15:97:96:e1:1d:0f:af:e5:85:27:88:d4"

  command-install-nr1-cli:
    steps:
      - run:
          name: "Install NR1 CLI"
          command: |
            if ! type "nr1" > /dev/null; then
              curl -s https://cli.nr-ext.net/installer.sh | sudo bash
            fi

  command-install-oss-cli:
    steps:
      - run:
          name: "Install OSS CLI"
          command: |
            npm install -g @newrelic/osscli
            
  # TO DO - Replace command-validate-nerdpack-schema and command-validate-opensource-files with the oss-cli
  # This will allow us to make changes at-will vs. updating dozens of config.yml's
  command-validate-nerdpack-schema:
    steps:
      - run:
          name: "Validating Nerdpack"
          command: |
            nr1 nerdpack:validate

  command-validate-opensource-files:
    steps:
      - run:
          name: "Checking for OSS files"
          command: |
            rootDir=./

            declare -a files=(
              "README.md"
              ".prettierrc.js"
              ".eslintrc.js"
              ".gitignore"
              ".circleci/config.yml"
              "package.json"

              "LICENSE"
              "THIRD_PARTY_NOTICES.md"
              "CODE_OF_CONDUCT.md"
              "cla.md"
              ".github/bug_report.md"
              ".github/enhancement.md"
            )

            for FILE in "${files[@]}"
            do
              if [ ! -f "${rootDir}$FILE" ]; then
                echo "$FILE is missing from Nerdpack"
                exit 1
              else
                echo "Found "${rootDir}$FILE
              fi
            done
  
  command-deploy-demotron:
    steps:
      - run:
          name: "Adding nr1 profile api key"
          command: |
            nr1 profiles:add --name demotronv2 --api-key $NR1CLI_PROFILE_DEMOTRONV2 --region us

      - run:
          name: "Build"
          command: |
            nr1 nerdpack:build

      - run:
          name: "Publish"
          command: |
            nr1 nerdpack:publish

      - run:
          name: "Deploy"
          command: |
            nr1 nerdpack:deploy

      - run:
          name: "Subscribe"
          command: |
            nr1 nerdpack:subscribe

jobs:
  job-setup:    
    executor: node10

    steps:
      - command-restore-or-checkout
      - command-install

  job-build:
    executor: node10browsers

    steps:
      - command-restore-or-checkout
      - command-install-nr1-cli
      - run:
          name: "nr1 nerdpack build"
          command: |
            nr1 nerdpack:build

  job-validate-nerdpack:
    executor: node10browsers

    steps:
      - command-restore-or-checkout
      - command-install-nr1-cli
      # TO DO - Build and publish the osscli to npm
      # - command-install-oss-cli
      - command-validate-nerdpack-schema
      - command-validate-opensource-files
  
  # Requires project to be setup and configured with eslint-plugin-newrelic
  job-lint:
    executor: node10browsers

    steps:
      - command-restore-or-checkout
      - command-install
      - run:
          name: "ESLinting"
          command: |
            npm run eslint-check

  job-test-pr:
    executor: node10browsers

    steps:
      - command-restore-or-checkout
      # We don't have tests yet, but we should
      - run:
          name: "Additional checks on pr from fork"
          command: |
            echo 'Validating nothing is awry, maybe we look for changes to package.json or .circle/config.yml'

  job-test-code:
    executor: node10browsers

    steps:
      - command-restore-or-checkout
      # We don't have tests yet, but we should
      - run: npm test

  # TO DO - Finish building out oss-cli contrib generator and publish oss-cli to npm
  job-generate-contributors:
    executor: node10browsers

    steps:
      - command-restore-or-checkout
      - command-setup-ci-keys
      # TO DO - Build and publish the osscli to npm
      # TO DO - Generate Contributors list
      # - command-install-oss-cli
      - run:
          name: Updating Contributors
          command: |
            CONTRIB_FILE=contributors.json

            # echo 'Generating a list of contributors'
            # echo 'oss generate:contributors --output=$CONTRIB_FILE'

            if [ -f "$CONTRIB_FILE" ]; then
              rm $CONTRIB_FILE
            fi

            touch $CONTRIB_FILE
            SAMPLE_CONTRIB_JSON='{"timestamp": "$(date)", "login":"devfreddy","id":197140,"node_id":"MDQ6VXNlcjE5NzE0MA==","avatar_url":"https://avatars1.githubusercontent.com/u/197140?v=4","gravatar_id":"","url":"https://api.github.com/users/devfreddy","html_url":"https://github.com/devfreddy","followers_url":"https://api.github.com/users/devfreddy/followers","following_url":"https://api.github.com/users/devfreddy/following{/other_user}","gists_url":"https://api.github.com/users/devfreddy/gists{/gist_id}","starred_url":"https://api.github.com/users/devfreddy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/devfreddy/subscriptions","organizations_url":"https://api.github.com/users/devfreddy/orgs","repos_url":"https://api.github.com/users/devfreddy/repos","events_url":"https://api.github.com/users/devfreddy/events{/privacy}","received_events_url":"https://api.github.com/users/devfreddy/received_events","type":"User","site_admin":false,"contributions":7}'
            echo $SAMPLE_CONTRIB_JSON > $CONTRIB_FILE

            if ! git diff-index --quiet HEAD --; then
              git config user.name "CircleCI Customer Journey"
              git config user.email "opensource+nr1-customer-journey-nerdpack@newrelic.com"
              git add $CONTRIB_FILE
              git commit -m "Updating contributors [skip ci]"
              git push origin $CIRCLE_BRANCH
            fi
  
  # TO DO - utilize our future oss-cli or a script to callout to github to generate a release utilizing the version in package.json
  job-generate-release:
    executor: node10browsers

    environment:
      <<: *github-semantic-bot

    steps:
      - command-restore-or-checkout
      - command-setup-ci-keys

      # https://semantic-release.gitbook.io/semantic-release/usage/plugins
      # Based on our current .releaserc, this will execute the following:
      #   execute @semantic-release/git
      #   execute the analyzeCommits implementation of @semantic-release/commit-analyzer
      #   execute the prepare implementation of @semantic-release/npm then @semantic-release/git
      #   execute the generateNotes implementation of @semantic-release/release-notes-generator
      - run:
          name: Semantic Release
          command: |
            npx semantic-release

  # TO DO - Profile keys (private env variables) & actual commands including adding --profile etc.
  job-deploy:
    executor: node10

    steps:
      - command-restore-or-checkout
      - command-install
      - command-install-nr1-cli
      - command-deploy-demotron

workflows:
  # A merge or commit to the master branch
  release:
    jobs:
      - job-setup:
          filters:
            branches:
              only:
                - master

      - job-build:
          requires:
            - job-setup

          filters:
            branches:
              only:
                - master
      
      - job-generate-contributors:
          requires:
            - job-setup
            - job-build

          filters:
            branches:
              only:
                - master

      - job-generate-release:
          requires:
            - job-setup
            - job-build

          filters:
            branches:
              only:
                - master

      # TO DO - Should deploy be based on the output of generating a release or the current state of the repo?
      - job-deploy:
          requires:
            - job-setup
            - job-build
            - job-generate-contributors
            - job-generate-release

          filters:
            branches:
              only:
                - master
  
  # Test and Analyze a branch (other than master)
  # Our Advanced Settings of "Only build pull requests" will limit this to branches with open pull requests
  analyze:
    jobs:
      - job-setup:
          filters:
            branches:
              ignore:
                - master
      
      - job-lint:
          requires:
            - job-setup

          filters:
            branches:
              ignore:
                - master

      # All contributions, even those by maintainers should follow the pr's from forks workflow
      # CircleCI sets the name of pull requests originating from forks to /pull/{id}
      - job-test-pr:
          requires:
            - job-setup

          filters:
            branches:
              only: /pull\/[0-9]+/

      - job-test-code:
          requires:
            - job-setup

          filters:
            branches:
              ignore:
                - master

      # Validate schema of the Nerdpack
      - job-validate-nerdpack:
          requires:
            - job-setup

          filters:
            branches:
              ignore:
                - master