# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# https://discuss.circleci.com/t/circleci-2-1-config-overview/26057
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    working_directory: ~/repo
    steps:
      # run tests!
      - run: npm test

  contributors:
    steps:
      - run:
        name: Generate Contributors
          command: |
            echo 'Generating a list of contributors'

workflows:
  build-and-test:
    jobs:
      - build
        filters:
          branches:
            only: circle-ci-test

      - test:
        requires:
          - build
        filters:
          branches:
            only: circle-ci-test

      - contributors:
        requires:
          - build
        filters:
          branches:
            only: circle-ci-test
